# CI and PR build script
#
# There should be no deep magic here. The developer experience and CI experience
# must remain as close to one another as possible.
#
# Developer experience:
#   npm install
#   (make changes)
#   npm test
#   vsce package
#   (give VSIX to someone for buddy testing)
trigger:
- master
- releases/*

steps:
- script: npm install
  displayName: npm install

# - script: npm test
#   displayName: npm test
#   continueOnError: true

# Set version number for PR/CI or release
- ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/releases/') }}:
  - template: ci/version-release.yml
- ${{ if not(startsWith(variables['Build.SourceBranch'], 'refs/heads/releases/')) }}:
  - template: ci/version-ci.yml

# HACK: comment out the magic schema imports that yaml-language-server adds
- script: npm run-script removeschemastore
  displayName: De-magic

# Acquire the `vsce` tool and use it to package
- script: |
    sudo npm install -g vsce
    vsce package
  displayName: Create VSIX

# This is how the CI system knows what to publish...
- task: CopyFiles@2
  displayName: Stage VSIX for publishing
  inputs:
    contents: '*.vsix' 
    targetFolder: $(Build.ArtifactStagingDirectory)

# ...and this is the CI system publishing it.
- task: PublishBuildArtifacts@1
  displayName: Publish VSIX
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: rocket-ship
